### ISSUE TITLE
Qual modelo de desenvolvimento vamos adotar?

### ISSUE THREAD

**Issue by arthurbarros** [arthurstaudt/loja-do-luciano#1]
Antes de começar a codar, queria saber qual modelo de desenvolvimento vamos adotar? MVC ?

**Comment by diogobenica** [comment]
Nossa, nem sei o que eu tava falando nos comentários acima haha

**Comment by arthurbarros** [comment]
É como entrar em uma maquina do tempo amigo!

**Comment by arthurstaudt** [comment]
kkkkkkkk

Como o tempo passa rápido em!
Temos que combinar algo para nos encontrar qualquer dia.
Saudades de todos

2015-02-18 10:20 GMT-02:00 Arthur Barros <notifications@github.com>:

> É como entrar em uma maquina do tempo amigo!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arthurstaudt/loja-do-luciano/issues/1#issuecomment-74855446>
> .
>



-- 
*Arthur Staudt*

**Comment by arthurbarros** [comment]
![WHAT THE FUCK?t](http://i.imgur.com/ukRjb5v.jpg)

**Comment by diogobenica** [comment]
Com certeza, @arthurstaudt! :beer:

**Comment by diogobenica** [comment]
@arthurbarros "dentor" é o codinome da spec do HTML6, nem manja hein rs

**Comment by arthurbarros** [comment]
@diogobenica Muito front-end pro meu gosto

On Wed, Feb 18, 2015 at 10:42 AM, Diogo Benicá <notifications@github.com>
wrote:

> @arthurbarros <https://github.com/arthurbarros> "dentor" é o codinome da
> spec do HTML6, nem manja hein rs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arthurstaudt/loja-do-luciano/issues/1#issuecomment-74857795>
> .
>



-- 
Atenciosamente,
Arthur Barros
http://github.com/arthurbarros
